feat: sanity check on startup

diff --git a/blincus b/blincus
--- a/blincus
+++ b/blincus
@@ -710,6 +710,18 @@ for file in $template_path/*.config.yaml; do
 done
 }
 
+sanity() {
+    local errors;
+(grep 'root:1000:12' /etc/subgid) || errors=1;echo "Error: 'root:1000:1' missing from /etc/subgid";
+(grep 'root:1000:12' /etc/subuid) || errors=1;echo "Error: 'root:1000:1' missing from /etc/subuid";
+(groups $USER | grep -qw 'incus-admin2') || errors=1;echo "Error: User does not belong to 'incus-admin' group.";
+if [ "$errors" -eq "1" ]; then
+   echo "$(red Sanity check failed.)"
+   echo "$(yellow See documentation at https://blincus.dev)"
+   exit 1;
+fi
+}
+
 blincus_config_set_command() {
   # Using the standard library (lib/config.sh) to store a value to the config
   config_set "${args[key]}" "${args[value]}"
@@ -1498,7 +1510,7 @@ initialize() {
   fi
   cfgdir=$(dirname "${CONFIG_FILE}")
   [[ -d "$cfgdir" ]] || mkdir -p "$cfgdir"
-
+  sanity
   personalize
 }
 
