fix: extract build to function to keep arguments

diff --git a/blincus b/blincus
--- a/blincus
+++ b/blincus
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.1.1 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.4 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
@@ -1043,7 +1043,7 @@ ini_keys() {
   for a in "${keys[@]}"; do echo "$a"; done | sort
 }
 
-image_id(){
+image_id() {
     local build=$1
     local manifest=$2
     #echo "build: $build"
@@ -1054,7 +1054,7 @@ image_id(){
 
 }
 
-image_alias(){
+image_alias() {
     local build=$1
     local manifest=$2
     #echo "build: $build"
@@ -1065,16 +1065,16 @@ image_alias(){
 
 }
 
-unique_builds(){
+unique_builds() {
     local build=$1
     cfgdir=$(dirname "${CONFIG_FILE}")
     workdir="${cfgdir}/packer"
-    builds=$(jq -r '.builds| group_by(.name) | .[][-1] | .name' "$workdir/$1.json" )
+    builds=$(jq -r '.builds| group_by(.name) | .[][-1] | .name' "$workdir/$1.json")
     # return builds as an array
     echo "$builds"
 }
 
-plugin(){
+plugin() {
     # check for packer plugin
     found=$(packer plugins installed | grep -q "incus" && echo "true" || echo "false")
 
@@ -1083,6 +1083,62 @@ plugin(){
         packer plugins install github.com/bketelsen/incus
     fi
 
+}
+
+packer_build() {
+    cfgdir=$(dirname "${CONFIG_FILE}")
+    name=$1
+    recipe="${cfgdir}/packer/${name}.pkr.hcl"
+    if [ ! -f "${recipe}" ]; then
+        echo "ERROR: recipe file not found: ${recipe}"
+        exit 1
+    fi
+
+    workdir="${cfgdir}/packer"
+    pushd "${workdir}" >/dev/null
+    packer build --force "${name}.pkr.hcl"
+    popd >/dev/null
+
+    ubuilds=$(unique_builds "${name}")
+    for build in ${ubuilds}; do
+        echo ""
+        echo "$(blue Build:) ${build}"
+        img_id=$(image_id "${build}" "${name}")
+        echo "  $(blue fingerprint:) ${img_id}"
+        alias=$(image_alias "${build}" "${name}")
+        echo "  $(blue alias:) ${alias}"
+        tmplt=$(blincus_get_property "${img_id}" "template")
+        echo "  $(blue template:) ${tmplt}"
+        scrpts=$(blincus_get_property "${img_id}" "scripts")
+        echo "  $(blue scripts:) ${scrpts}"
+
+        # ensure sourcetemplate exists
+        if [ ! -e "${cfgdir}/templates/${tmplt}.config.yaml" ]; then
+            echo "Source template $(red ${tmplt}) does not exist"
+            exit 1
+        fi
+        # ensure scriptdir exists
+        if [ ! -e "${cfgdir}/scripts/${scrpts}" ]; then
+            echo "Script directory $(red ${scrpts}) does not exist"
+            exit 1
+        fi
+
+        local imageref
+        # if alias is set, use it
+        if [ -n "${alias}" ]; then
+            imageref="${alias}"
+        else
+            imageref="${img_id}"
+        fi
+
+        # Create config values for this image
+        config_set "packer-${name}.image" "${imageref}"
+        config_set "packer-${name}.scripts" "${scrpts}"
+
+        # copy image template
+        cp "${cfgdir}/templates/${tmplt}.config.yaml" "${cfgdir}/templates/packer-${name}.config.yaml"
+
+    done
 }
 
 personalize() {
@@ -1358,64 +1414,16 @@ blincus_template_restore_command() {
 }
 
 blincus_packer_build_command() {
-  cfgdir=$(dirname "${CONFIG_FILE}")
   name=${args[name]}
 
+  # make sure we have the packer plugin
   plugin
 
+  # make sure the templates are personalized
   personalize
 
-  recipe="${cfgdir}/packer/${name}.pkr.hcl"
-  if [ ! -f "${recipe}" ]; then
-      echo "ERROR: recipe file not found: ${recipe}"
-      exit 1
-  fi
-
-  workdir="${cfgdir}/packer"
-  pushd "${workdir}" >/dev/null
-  packer build --force "${name}.pkr.hcl"
-  popd >/dev/null
-
-  ubuilds=$(unique_builds "${name}")
-  for build in ${ubuilds}; do
-      echo ""
-      echo "$(blue Build:) ${build}"
-      img_id=$(image_id "${build}" "${name}")
-      echo "  $(blue fingerprint:) ${img_id}"
-      alias=$(image_alias "${build}" "${name}")
-      echo "  $(blue alias:) ${alias}"
-      tmplt=$(blincus_get_property "${img_id}" "template")
-      echo "  $(blue template:) ${tmplt}"
-      scrpts=$(blincus_get_property "${img_id}" "scripts")
-      echo "  $(blue scripts:) ${scrpts}"
-
-      # ensure sourcetemplate exists
-      if [ ! -e "${cfgdir}/templates/${tmplt}.config.yaml" ]; then
-          echo "Source template $(red ${tmplt}) does not exist"
-          exit 1
-      fi
-      # ensure scriptdir exists
-      if [ ! -e "${cfgdir}/scripts/${scrpts}" ]; then
-          echo "Script directory $(red ${scrpts}) does not exist"
-          exit 1
-      fi
-
-      local imageref
-      # if alias is set, use it
-      if [ -n "${alias}" ]; then
-          imageref="${alias}"
-      else
-          imageref="${img_id}"
-      fi
-
-      # Create config values for this image
-      config_set "packer-${name}.image" "${imageref}"
-      config_set "packer-${name}.scripts" "${scrpts}"
-
-      # copy image template
-      cp "${cfgdir}/templates/${tmplt}.config.yaml" "${cfgdir}/templates/packer-${name}.config.yaml"
-
-  done
+  # build the packer image
+  packer_build $name
 }
 
 blincus_packer_buildall_command() {
@@ -1429,7 +1437,7 @@ blincus_packer_buildall_command() {
       name="$(basename "${file}" .pkr.hcl)"
       echo ""
   	echo "Found definition $(red_bold $name):"
-      blincus_packer_build_command $name
+      packer_build $name
 
   done
 
@@ -2456,7 +2464,7 @@ initialize() {
   if [ "$BLINCUS_SKIP_SANITY" != 1 ] ; then
     sanity
   fi
-  personalize
+  #personalize
   prompt_reconcile
 
 }
